# Generated by Django 5.0.11 on 2025-01-28 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_attendance_face_recognition_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='salt',
            field=models.CharField(editable=False, max_length=32),
        ),
    ]
