# Generated by Django 5.0.11 on 2025-01-29 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_session_salt'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='face_recognition_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='session',
            name='location_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
